name: Release

on:
  release:
    types: [published]

jobs:
  deploy-cocoapods:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bundled Gems
        run: bundle install --without=documentation --jobs 4 --retry 3
      - name: Deploy to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: bundle exec pod trunk push --allow-warnings

  info:
    runs-on: macOS-latest
    steps:
      - name: Show Ruby version
        run: ruby --version
      - name: Show Bundler version
        run: bundle version
